language: node_js
node_js: 
  - stable
services:
  - postgresql 9.6
install :
  - npm install
env:
  global: 
    - DATABASE_URL=postgres://gcyngqxo:6Q5c7AbgpaeSRU2ZRO74tojCYOf88d03@stampy.db.elephantsql.com:5432/gcyngqxo
before script:
  - 
script: 
  - npm run test
after_success: 
  - npm run coverage