language: node_js
node_js: 
  - stable
install :
  - npm install
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c "CREATE DATABASE sendit_test;" -U postgres
script: 
  - npm run test
after_success: 
  - npm run coverage