language: node_js
node_js: 
  - stable
install :
  - npm install
script: 
  - npm run test
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
after_success: 
  - npm run coverage