const users = [
	{ id: 1, Name: 'Emmanuel O.', phoneNumber: '08138015039', email: 'emmanueloboh04@gmail.com', username: 'Awesome Kelly', password: 'senSe001', category: 'admin' },
	{ id: 2, Name: 'Michael O.', phoneNumber: '07063823938', email: 'kellyharper2k4@yahoo.com', username: 'Micky', password: 'obOh1999', category: 'user' },
	{ id: 3, Name: 'Aaron O.', phoneNumber: '08053467873', email: 'awesomekelly04@outlook.com', username: 'Dreamer', password: 'aarOn002', category: 'user' }
];

const parcels = [
	{ id: 1, parcelName: 'Television', parcelValue: 'N54,000.00', parcelWeight: '12kg', parcelLength: '12cm', parcelwidth: '12cm', parcelheight: '12cm', parcelFee: 'N1,000', collectionAddressLine1: 'JQ 17, FMW&H Qrts', collectionAddressLine2: 'Barnawa', collectionCity: 'Kaduna', collectionState: 'Kaduna', collectionDate: '8/11/2018', destinationAddressLine1: 'Behind Police Signboard, Airport Road', destinationAddressLine2: 'Lugbe', destinationCity: 'Abuja', destinationState: 'FCT', userId: 2, parcelStatus: 'Delivered', currentLocationAddressLine1: 'Behind Police Signboard, Airport Road', currentLocationAddressLine2: 'Lugbe', currentLocationCity: 'Abuja', currentLocationState: 'FCT', dateOfUpdate: '8/11/2018', timeOfUpdate: '3:00pm'},
	{ id: 2, parcelName: 'Stove', parcelValue: 'N5,000.00', parcelWeight: '6kg', parcelLength: '12cm', parcelwidth: '12cm', parcelheight: '12cm', parcelFee: 'N1,000', collectionAddressLine1: 'JQ 17, FMW&H Qrts', collectionAddressLine2: 'Barnawa', collectionCity: 'Kaduna', collectionState: 'Kaduna', collectionDate: '8/11/2018', destinationAddressLine1: 'Behind Police Signboard, Airport Road', destinationAddressLine2: 'Lugbe', destinationCity: 'Abuja', destinationState: 'FCT', userId: 2, parcelStatus: 'On Transit', currentLocationAddressLine1: 'Kaduna Road', currentLocationAddressLine2: '', currentLocationCity: 'Kaduna', currentLocationState: 'Kaduna', dateOfUpdate: '8/11/2018', timeOfUpdate: '3:00pm'},
	{ id: 3, parcelName: 'Radio', parcelValue: 'N44,000.00', parcelWeight: '13kg', parcelLength: '12cm', parcelwidth: '12cm', parcelheight: '12cm', parcelFee: 'N1,000', collectionAddressLine1: 'JQ 17, FMW&H Qrts', collectionAddressLine2: 'Barnawa', collectionCity: 'Kaduna', collectionState: 'Kaduna', collectionDate: '8/11/2018', destinationAddressLine1: 'Behind Police Signboard, Airport Road', destinationAddressLine2: 'Lugbe', destinationCity: 'Abuja', destinationState: 'FCT', userId: 2, parcelStatus: '', currentLocationAddressLine1: 'Zuba', currentLocationAddressLine2: 'Lugbe', currentLocationCity: 'Abuja', currentLocationState: 'FCT', dateOfUpdate: '8/11/2018', timeOfUpdate: '3:00pm'},
	{ id: 4, parcelName: 'Laptop', parcelValue: 'N154,000.00', parcelWeight: '3kg', parcelLength: '12cm', parcelwidth: '12cm', parcelheight: '12cm', parcelFee: 'N1,000', collectionAddressLine1: 'JQ 17, FMW&H Qrts', collectionAddressLine2: 'Barnawa', collectionCity: 'Kaduna', collectionState: 'Kaduna', collectionDate: '8/11/2018', destinationAddressLine1: 'Behind Police Signboard, Airport Road', destinationAddressLine2: 'Lugbe', destinationCity: 'Abuja', destinationState: 'FCT', userId: 3, parcelStatus: 'On Transit', currentLocationAddressLine1: 'Garki', currentLocationAddressLine2: 'Lugbe', currentLocationCity: 'Abuja', currentLocationState: 'FCT', dateOfUpdate: '8/11/2018', timeOfUpdate: '3:00pm'},
	{ id: 5, parcelName: 'Shoes', parcelValue: 'N15,000.00', parcelWeight: '1kg', parcelLength: '12cm', parcelwidth: '12cm', parcelheight: '12cm', parcelFee: 'N1,000', collectionAddressLine1: 'JQ 17, FMW&H Qrts', collectionAddressLine2: 'Barnawa', collectionCity: 'Kaduna', collectionState: 'Kaduna', collectionDate: '8/11/2018', destinationAddressLine1: 'Behind Police Signboard, Airport Road', destinationAddressLine2: 'Lugbe', destinationCity: 'Abuja', destinationState: 'FCT', userId: 3, parcelStatus: 'Delivered', currentLocationAddressLine1: 'Behind Police Signboard, Airport Road', currentLocationAddressLine2: 'Lugbe', currentLocationCity: 'Abuja', currentLocationState: 'FCT', dateOfUpdate: '8/11/2018', timeOfUpdate: '3:00pm'},
];